const ROUTES_CONSTANTS_POSTS = "/";
const ROUTES_CONSTANTS_POST= "/:id";
const ROUTES_CONSTANTS_POST_ADD= "/add";
const ROUTES_CONSTANTS_CATEGORIES= "/category";
const ROUTES_CONSTANTS_CATEGORY= "/category:id";
const ROUTES_CONSTANTS_LOGIN= "/login";
const ROUTES_CONSTANTS_REGISTRATION= "/registration";

export {
    ROUTES_CONSTANTS_POSTS,
    ROUTES_CONSTANTS_POST,
    ROUTES_CONSTANTS_CATEGORIES,
    ROUTES_CONSTANTS_CATEGORY,
    ROUTES_CONSTANTS_LOGIN,
    ROUTES_CONSTANTS_REGISTRATION,
    ROUTES_CONSTANTS_POST_ADD
};